config/routes.rb
Focusadmin::Engine.routes.draw do
	root 'dashboard#index'
  get 'rankings' => 'dashboard#rankings'
  get 'review' => 'articles#review'
  get 'scheduled' => 'articles#scheduled'
	resources :users
  get 'curator_applicants' => 'users#curator_applicants', as: "curator_applicants"
	resources :admins
  resources :comments
  resources :pickups
  resources :information
  resources :contents
  resources :settings
  get 'settings/:id/edit_pages' => 'settings#edit_pages', as: "edit_page_setting"

  get 'items/products' => 'items#products'
  get 'items/events' => 'items#events'
  get 'tags', :to => 'tag#index'

  resources :categories do
    post :update_row_order, on: :collection
  end

  resources :banners do
    post :update_row_order, on: :collection
  end

	resources :articles do
    get 'update_status', on: :collection
  end

  resources :areas do
    post :update_row_order, on: :collection
  end

  resources :features do
    post :update_row_order, on: :collection
  end

  resources :faqs do
    post :update_row_order, on: :collection
  end

end

app/controllers/focusadmin/admins_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class AdminsController < ApplicationController
  	before_action :set_admin, only: [:show, :edit, :update, :destroy]

    def index
    	@admins = Admin.all
    end

	  def new
	    @admin = Admin.new
	  end

	  def edit
	  end

	  def create
	    @admin = Admin.new(admin_params)

	    respond_to do |format|
	      if @admin.save
	        format.html { redirect_to admins_url, notice: 'Admin was successfully created.' }
	      else
	        format.html { render :new }
	        format.json { render json: @admin.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def update
	    respond_to do |format|
	      if @admin.update(admin_params)
	        format.html { redirect_to admins_url, notice: 'Admin was successfully updated.' }
	      else
	        format.html { render :edit }
	        format.json { render json: @admin.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def destroy
	    @admin.destroy
	    respond_to do |format|
	      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

    private
      def set_admin
        @admin = Admin.find(params[:id])
      end

	    def admin_params
	      params.require(:admin).permit(:email, :password, :password_confirmation)
	    end

  end
end

app/controllers/focusadmin/application_controller.rb
module Focusadmin
  class ApplicationController < ::ApplicationController
  	before_action :authenticate_admin!
  	#layout "application"
  end
end

app/controllers/focusadmin/areas_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class AreasController < ApplicationController
    before_action :set_area, only: [:edit, :update, :destroy]

    def update_row_order
      @area = Area.find(area_params[:area_id])
      @area.row_order_position = area_params[:row_order_position]
      @area.save

      render nothing: true
    end

    def index
      @areas = Area.rank(:row_order).all
    end

    def new
      @area = Area.new
    end

    def edit
    end

    def create
      @area = Area.new(area_params)

      respond_to do |format|
        if @area.save
          format.html { redirect_to areas_url, notice: 'area was successfully created.' }
          format.json { render :index, status: :created, location: @area }
        else
          format.html { render :new }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @area.update(area_params)
          format.html { redirect_to areas_url, notice: 'area was successfully updated.' }
          format.json { render :index, status: :ok, location: @area }
        else
          format.html { render :edit }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      def set_area
        @area = Area.find(params[:id])
      end

      def area_params
        params.require(:area).permit(:name, :slug, :description, :visibility, :ancestry, :thumbnail, :thumbnail2, :thumbnail3, :row_order_position, :area_id)
      end

  end
end

app/controllers/focusadmin/articles_controller.rb
require_dependency "focusadmin/application_controller"
require "koala"
require "twitter"

module Focusadmin
  class ArticlesController < ApplicationController
    include CloudinaryHelper
    before_action :set_article, only: [:edit, :update]

    def index
      @q = Article.all.includes(:user).ransack(params[:q])
      @articles = @q.result(distinct: true).order(id: "DESC").page(params[:page]).per(100)

      articles_published = Article.where(status: "published")
      @articles_published_count = articles_published.count
    end

    def edit
    end

    def update
      if params[:article].present? and params[:article][:title].present?
        @article.update(article_params)
        respond_to do |format|
          format.html { redirect_to articles_url, notice: 'article was successfully updated.' }
        end
      else

      	if params[:status_change_button] == "下書きに戻す" || params[:status_change_button] == "Unpublish"
  		    respond_to do |format|
  		      @article.status = "draft"
  		      @article.save
  		      @article_id = @article.id
  		      @action = "change_to_draft"
  		      format.js
  		    end
  		  elsif params[:status_change_button] == "差し戻す" || params[:status_change_button] == "Reject"
  		    respond_to do |format|
  		      @article.status = "draft"
  		      @article.rejected_at = Time.zone.now
  		      @article.reject_reason = params[:reject_reason]
  		      @article.reject_message = params[:reject_message]
  		      @article.save
  		      @action = "reject"
  		      ArticleMailer.review_result_notification_email(@article.user, @article, @action).deliver_later
	      	  format.html { redirect_to review_url, notice: t('.article_has_been_rejected') }
  		    end
        elsif params[:status_change_button] == "公開を予約する" || params[:status_change_button] == "Publish on Schedule"
          respond_to do |format|
            @article.status = "scheduled"

            if params[:facebook].present?
              @article.facebook_post = params[:facebook_post_message] if params[:facebook][:post] == "true" #params come in as strings
            end

            if params[:twitter].present?
              @article.twitter_post = params[:twitter_post_message] if params[:twitter][:post] == "true" #params come in as strings
            end

            article = params[:article]
            @article.publish_on_schedule_at = Time.new(article["publish_on_schedule_at(1i)"].to_i, article["publish_on_schedule_at(2i)"].to_i, article["publish_on_schedule_at(3i)"].to_i, article["publish_on_schedule_at(4i)"].to_i, article["publish_on_schedule_at(5i)"].to_i)
            @article.save
            @action = "scheduled"
            format.html { redirect_to review_url, notice: t('.article_has_been_scheduled') }
          end
        elsif params[:cancel_schedule_button] == "キャンセル" || params[:cancel_schedule_button] == "Cancel"
          respond_to do |format|
            @article.status = "reviewing"
            @article.publish_on_schedule_at = ""
            @article.save
            @article_id = @article.id
            @action = "cancelled_schedule"
            format.js
          end
        else
          respond_to do |format|
            @article.status = "published"
            @article.published_at = Time.zone.now
            @article.save
            @article_id = @article.id
            @action = "publish"
            ArticleMailer.review_result_notification_email(@article.user, @article, @action).deliver_later

            if params[:facebook].present?
              post_to_facebook(params[:facebook_post_message]) if params[:facebook][:post] == "true" #params come in as strings
            end

            if params[:twitter].present?
              tweet(params[:twitter_post_message]) if params[:twitter][:post] == "true" #params come in as strings
            end

            format.html { redirect_to review_url, notice: t('.article_has_been_published') }
          end
        end

      end
    end

    def review
      @q = Article.reviewing.includes(:user).ransack(params[:q])
      @articles = @q.result(distinct: true).order(id: "DESC")
      @articles_waiting_review = Article.reviewing.includes(:user).includes(:category).order(updated_at: :desc)
      @articles_waiting_review_count = @articles_waiting_review.count
    end

    def scheduled
      @q = Article.scheduled.includes(:user).ransack(params[:q])
      @articles = @q.result(distinct: true).order(id: "DESC")
      @scheduled_articles = Article.scheduled.includes(:user).order(publish_on_schedule_at: :asc)
      @scheduled_articles_count = @scheduled_articles.count
    end

	  private
	    def set_article
	      @article = Article.find(params[:id])
	    end

	    def article_params
	      params.require(:article).permit(:title, :excerpt, :body, :slug, :thumbnail, :category_id, :status, :tag_list, :published_at, :rejected_at, :reject_reason, :reject_message, :publish_on_schedule_at, :initially_submitted_at,
          :facebook, :facebook_post_message, :twitter, :twitter_post_message,
          :pr, :sponsor, :pr_start, :pr_end, :pr_pickup)
	    end

      def tweet(twitter_post_message)

        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
          config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
          config.access_token        = ENV['TWITTER_ACCESS_TOKEN']
          config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
        end

        client.update(twitter_post_message + "\nhttps://#{ENV['CANONICAL_HOST']}/#{@article.id}")
      end

      def post_to_facebook(facebook_post_message)

        image_url = cl_image_path(@article.thumbnail, :width => 1200)
        @api = Koala::Facebook::API.new(ENV['FACEBOOK_PAGE_ACCESS_TOKEN'])
        @api.put_wall_post(facebook_post_message, {
          "name" => @article.title,
          "link" => "https://#{ENV['CANONICAL_HOST']}/#{@article.id}", # must be absolute path
          "description" => @article.excerpt,
          "picture" => image_url
        })

      end

  end
end

app/controllers/focusadmin/banners_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class BannersController < ApplicationController
    before_action :set_banner, only: [:show, :edit, :update, :destroy]

    def update_row_order
      @banner = Banner.find(banner_params[:banner_id])
      @banner.row_order_position = banner_params[:row_order_position]
      @banner.save

      render nothing: true
    end

    def index
      @banners = Banner.rank(:row_order)
    end

    def new
      @banner = Banner.new
    end

    def create
      @banner = Banner.new(banner_params)

      respond_to do |format|
        if @banner.save
          format.html { redirect_to banners_url, notice: 'Banner was successfully created.' }
          format.json { render :show, status: :created, location: @banner }
        else
          format.html { render :new }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @banner.update(banner_params)
          format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
          format.json { render :show, status: :ok, location: @banner }
        else
          format.html { render :edit }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @banner.destroy
      respond_to do |format|
        format.html { redirect_to banners_url, notice: 'Banner was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_banner
        @banner = Banner.find(params[:id])
      end

      def banner_params
        params.require(:banner).permit(:banner, :link, :target, :memo, :row_order, :row_order_position, :banner_id)
      end

  end

end

app/controllers/focusadmin/categories_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class CategoriesController < ApplicationController
	  before_action :set_category, only: [:edit, :update, :destroy]

  	def update_row_order
  	  @category = Category.find(category_params[:category_id])
  	  @category.row_order_position = category_params[:row_order_position]
  	  @category.save

  	  render nothing: true
  	end

    def index
    	@categories = Category.rank(:row_order)
    end

	  def new
	    @category = Category.new
	  end

	  def edit
	  end

	  def create
	    @category = Category.new(category_params)

	    respond_to do |format|
	      if @category.save
	        format.html { redirect_to categories_url, notice: 'category was successfully created.' }
	        format.json { render :index, status: :created, location: @category }
	      else
	        format.html { render :new }
	        format.json { render json: @category.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def update
	    respond_to do |format|
	      if @category.update(category_params)
	        format.html { redirect_to categories_url, notice: 'category was successfully updated.' }
	        format.json { render :index, status: :ok, location: @category }
	      else
	        format.html { render :edit }
	        format.json { render json: @category.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def destroy
	    @category.destroy
	    respond_to do |format|
	      format.html { redirect_to categories_url, notice: 'category was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

	  private
	    def set_category
	      @category = Category.find(params[:id])
	    end

	    def category_params
	      params.require(:category).permit(:name, :description, :slug, :thumbnail, :icon, :row_order, :row_order_position, :category_id)
	    end
  end
end

app/controllers/focusadmin/comments_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class CommentsController < ApplicationController

    def index
      @comments_count = Comment.all.count
    	@comments = Comment.all.includes(:user).order(id: "DESC")
    end

  end
end

app/controllers/focusadmin/contents_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_url, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_url, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :body, :slug, :status)
    end

	end
end

app/controllers/focusadmin/items_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    def products
      @q = Item.where(item_type: "product").includes(:article).ransack(params[:q])
      @items = @q.result(distinct: true).order(created_at: "DESC").page params[:page]
    end

    def events
      @events = Item.where(item_type: "event").includes(:article).order(event_start_date: :desc)
    end

    private
      def set_item
        @item = Item.find(params[:id])
      end

  end
end

app/helpers/focusadmin/application_helper.rb
module Focusadmin
  module ApplicationHelper

    def curator_page_path(username)
      if username.present?
      escaped_username = URI.escape(username)
      return main_app.root_path + "c/" + escaped_username
      else
        return main_app.root_path
      end
    end

  end
end

app/helpers/focusadmin/articles_helper.rb
module Focusadmin
  module ArticlesHelper

  	def status_view(article)
  		case  article.status
  		when "published" then
  			return t('.published')
      when "reviewing" then
        return t('.reviewing')
  		when "draft" then
        if article.rejected_at.present?
          return t('.rejected')
        else
    			return t('.draft')
        end
  		end
  	end

  end
end

app/helpers/focusadmin/comments_helper.rb
module Focusadmin
  module CommentsHelper

  	def commented_article(comment)
      @article = Article.find(comment.commentable_id)
  	end

  end
end

app/views/focusadmin/settings/_form.html.erb
<%= simple_form_for(@setting, html: { class: 'form-vertical' }) do |f| %>
<div class="row">
  <div class="col-xs-1"><%= f.input :locale, hint: 'en or ja only; Setting this incorrectly will crash the site' %></div>
  <div class="col-xs-3"><%= f.input :site_name_supplement %></div>
  <div class="col-xs-8"><%= f.input :catch, hint: 'Short Text' %></div>
</div>
<div class="row">
  <div class="col-xs-6">
    <div class="preview">
      <% if @setting.site_logo_image.present? %>
        <%= cl_image_tag @setting.site_logo_image, :width => 320, :sign_url => true, :class => "img-responsive" %>
      <% end %>
    </div>
    <%= f.label :site_logo_image %><br>
    <%= cl_image_upload_tag('setting[site_logo_image]', :tags => "setting", :crop => :limit, :width => 750, :height => 750) %>
  </div>
  <div class="col-xs-6">
  <%= f.label :sp_site_logo_image %><br>
  <%= cl_image_upload_tag('setting[sp_site_logo_image]', :tags => "setting", :crop => :limit, :width => 750, :height => 750) %>
  <%= f.label :smartnews_logo_image %><br>700px x 100px
  <%= cl_image_upload_tag('setting[smartnews_logo_image]', :tags => "setting", :crop => :limit, :width => 700, :height => 100) %>
  <%= f.label :footer_logo_image %><br>
  <%= cl_image_upload_tag('setting[footer_logo_image]', :tags => "setting", :crop => :limit) %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
  <%= f.input :meta_description, hint: 'Recommended Length: 50 characters for Mobile, 120 characters for Desktop' %>
  <%= f.input :og_description %>

  <%= f.label :og_image %><br>Use images that are at least 1200 x 630 pixels.
  <%= cl_image_upload_tag('setting[og_image]', :tags => "setting", :crop => :limit, :width => 750, :height => 750) %>

  <%= f.label :favicon %><br>File name should be favicon.ico; size is 32px x 32px
  <%= cl_image_upload_tag('setting[favicon]', :tags => "setting", :crop => :limit, :width => 750, :height => 750) %>

  <%= f.label :apple_touch_icon %><br>File extension should be png; size is 192px x 192px
  <%= cl_image_upload_tag('setting[apple_touch_icon]', :tags => "setting", :crop => :limit, :width => 750, :height => 750) %>
  </div>
</div>
<div class="row">
  <div class="col-xs-3">
    <%= f.input :facebook_page_url %>
  </div>
  <div class="col-xs-3">
    <%= f.input :twitter_account_url %>
  </div>
  <div class="col-xs-3">
    <%= f.input :instagram_account_url %>
  </div>
  <div class="col-xs-3">
    <%= f.input :line_account_url %>
  </div>
</div>
<div class="row">
  <div class="col-xs-6">
    <%= f.input :exclude_tags %>
  </div>
  <div class="col-xs-6">
    <%= f.input :exclude_brands %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= f.input :recent_articles_tab_text %>
    <hr>
    
    <%= f.input :welcome_page_url %>
    <%= f.input :author %>
    <%= f.input :author_url %>
    <%= f.input :author_url_anchor_text %>

    <hr>
    <%= f.input :free_field1_question %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
   <%= f.button :submit, "変更する", class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/focusadmin/settings/edit.html.erb
<h1><%= ENV['SITE_NAME'] %>サイト設定の変更</h1>

<%= render 'form' %>

<hr>
<%= link_to '戻る', settings_path %>

app/views/focusadmin/settings/edit_pages.html.erb
<h1><%= ENV['SITE_NAME'] %>静的ページコンテンツ</h1>

<%= simple_form_for(@setting, html: { class: 'form-vertical' }) do |f| %>
<div class="row">
  <div class="col-xs-8">
    <%= f.input :concept_page_html %>
    <%= f.input :privacy_page_html %>
    <%= f.input :terms_page_html %>
    <%= f.input :curator_terms_page_html %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
   <%= f.button :submit, "変更する", class: "btn btn-primary" %>
  </div>
</div>
<% end %>


<hr>
<%= link_to '戻る', settings_path %>

app/views/focusadmin/settings/index.html.erb
<h1 class="pull-left"><%= t('.settings') %>&nbsp;<small><%= t('.current_language') %>: <%= ENV['DEFAULT_LOCALE'] %></small></h1>

<div class="dropdown pull-right" style="margin-top:20px;">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <%= t('.other_settings') %>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to t('.faqs'), faqs_path %></li>
    <li><%= link_to t('.categories'), categories_path %></li>
    <li><%= link_to t('.areas'), areas_path %></li>
    <li><%= link_to t('.pages'), contents_path %></li>
    <li><%= link_to t('.admins'), admins_path %></li>
  </ul>
</div>

<hr style="clear:both;"/>
<h3>Site Info</h3>

<table class="table">
  <thead>
    <tr>
      <th>locale</th>
      <th>title</th>
      <th>LOGO</th>
      <th>Meta description</th>
      <th>og:description</th>
      <th>Catch for email</th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><h3><%= setting.locale %></h3><%= link_to t('.edit'), edit_setting_path(setting) %><hr><%= link_to t('.edit_page'), edit_page_setting_path(setting) %></td>
        <td>top title:<h4><%= ENV['SITE_NAME'] %><%= setting.site_name_supplement %></h4>title:<h4><%= ENV['SITE_NAME'] %></h4></td>
        <td>
          <% if setting.site_logo_image.present? %>
          pc: <%= cl_image_tag setting.site_logo_image, :width => 160, :sign_url => true, :class => "img-responsive" %>
          <% end %><br>
          <% if setting.sp_site_logo_image.present? %>
          sp: <%= cl_image_tag setting.sp_site_logo_image, :width => 160, :sign_url => true, :class => "img-responsive" %>
          <% end %>
        </td>
        <td><%= setting.meta_description %></td>
        <td><%= setting.og_description %></td>
        <td><%= setting.catch %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Settings</h3>

<table class="table">
  <thead>
    <tr>
      <th>locale</th>
      <th>images</th>
      <th>social media</th>
      <th>Author</th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.locale %></td>
        <td>
          <% if setting.og_image.present? %>og:image
           <%= cl_image_tag setting.og_image, :width => 160, :sign_url => true, :class => "img-responsive" %>
          <% end %>
          <% if setting.favicon.present? %>favicon
           <%= cl_image_tag setting.favicon, :width => 160, :sign_url => true, :class => "img-responsive" %>
          <% end %>
          <% if setting.apple_touch_icon.present? %>Apple touch icon
            <%= cl_image_tag setting.apple_touch_icon, :width => 160, :sign_url => true, :class => "img-responsive" %>
          <% end %>
          <% if setting.footer_logo_image.present? %>Footer logo image
            <%= cl_image_tag setting.footer_logo_image, :sign_url => true, :class => "img-responsive" %>
          <% end %>
        </td>
        <td>
        <% if setting.facebook_page_url.present? %>facebook:<br><%= link_to "https://www.facebook.com/" + setting.facebook_page_url.to_s + "/", "https://www.facebook.com/" + setting.facebook_page_url.to_s + "/", target: "_blank" %><br><% end %>
        <% if setting.twitter_account_url.present? %>twitter:<br><%= link_to "https://twitter.com/" + setting.twitter_account_url.to_s, "https://twitter.com/" + setting.twitter_account_url.to_s, target: "_blank" %><br><% end %>
        <% if setting.instagram_account_url.present? %>instagram:<br><%=  link_to "https://www.instagram.com/" + setting.instagram_account_url.to_s + "/", "https://www.instagram.com/" + setting.instagram_account_url.to_s + "/", target: "_blank" %><br><% end %>
        <% if setting.line_account_url.present? %>LINE:<br><%=  link_to "https://page.line.me/" + setting.line_account_url.to_s + "/", "https://page.line.me/" + setting.line_account_url.to_s + "/", target: "_blank" %><% end %>
        </td>
        <td><%= link_to setting.author_url_anchor_text, setting.author_url, target: "_blank" %> (<%= setting.author %>)</td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Content</h3>

<table class="table">
  <thead>
    <tr>
      <th>locale</th>
      <th>exclude_tags</th>
      <th>exclude_brands</th>
      <th>Pages</th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.locale %></td>
        <td><%= setting.exclude_tags %></td>
        <td><%= setting.exclude_brands %></td>
        <td><%= link_to "Concept", main_app.concept_path, target: "_blank" %><br>
        <%= link_to "Privacy Policy", main_app.privacy_path, target: "_blank" %><br>
        <%= link_to "Terms", main_app.terms_path, target: "_blank" %><br>
        <%= link_to "Welcome", setting.welcome_page_url, target: "_blank" if setting.welcome_page_url.present? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/focusadmin/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>