config/routes.rb
Focusadmin::Engine.routes.draw do
	root 'dashboard#index'
  get 'rankings' => 'dashboard#rankings'
  get 'review' => 'articles#review'
  get 'scheduled' => 'articles#scheduled'
	resources :users
  get 'curator_applicants' => 'users#curator_applicants', as: "curator_applicants"
	resources :admins
  resources :comments
  resources :pickups
  resources :information
  resources :contents
  resources :settings
  get 'settings/:id/edit_pages' => 'settings#edit_pages', as: "edit_page_setting"

  get 'items/products' => 'items#products'
  get 'items/events' => 'items#events'
  get 'tags', :to => 'tag#index'

  resources :categories do
    post :update_row_order, on: :collection
  end

  resources :banners do
    post :update_row_order, on: :collection
  end

	resources :articles do
    get 'update_status', on: :collection
  end

  resources :areas do
    post :update_row_order, on: :collection
  end

  resources :features do
    post :update_row_order, on: :collection
  end

  resources :faqs do
    post :update_row_order, on: :collection
  end

end

app/controllers/focusadmin/admins_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class AdminsController < ApplicationController
  	before_action :set_admin, only: [:show, :edit, :update, :destroy]

    def index
    	@admins = Admin.all
    end

	  def new
	    @admin = Admin.new
	  end

	  def edit
	  end

	  def create
	    @admin = Admin.new(admin_params)

	    respond_to do |format|
	      if @admin.save
	        format.html { redirect_to admins_url, notice: 'Admin was successfully created.' }
	      else
	        format.html { render :new }
	        format.json { render json: @admin.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def update
	    respond_to do |format|
	      if @admin.update(admin_params)
	        format.html { redirect_to admins_url, notice: 'Admin was successfully updated.' }
	      else
	        format.html { render :edit }
	        format.json { render json: @admin.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def destroy
	    @admin.destroy
	    respond_to do |format|
	      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

    private
      def set_admin
        @admin = Admin.find(params[:id])
      end

	    def admin_params
	      params.require(:admin).permit(:email, :password, :password_confirmation)
	    end

  end
end

app/controllers/focusadmin/application_controller.rb
module Focusadmin
  class ApplicationController < ::ApplicationController
  	before_action :authenticate_admin!
  	#layout "application"
  end
end

app/controllers/focusadmin/areas_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class AreasController < ApplicationController
    before_action :set_area, only: [:edit, :update, :destroy]

    def update_row_order
      @area = Area.find(area_params[:area_id])
      @area.row_order_position = area_params[:row_order_position]
      @area.save

      render nothing: true
    end

    def index
      @areas = Area.rank(:row_order).all
    end

    def new
      @area = Area.new
    end

    def edit
    end

    def create
      @area = Area.new(area_params)

      respond_to do |format|
        if @area.save
          format.html { redirect_to areas_url, notice: 'area was successfully created.' }
          format.json { render :index, status: :created, location: @area }
        else
          format.html { render :new }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @area.update(area_params)
          format.html { redirect_to areas_url, notice: 'area was successfully updated.' }
          format.json { render :index, status: :ok, location: @area }
        else
          format.html { render :edit }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      def set_area
        @area = Area.find(params[:id])
      end

      def area_params
        params.require(:area).permit(:name, :slug, :description, :visibility, :ancestry, :thumbnail, :thumbnail2, :thumbnail3, :row_order_position, :area_id)
      end

  end
end

app/controllers/focusadmin/articles_controller.rb
require_dependency "focusadmin/application_controller"
require "koala"
require "twitter"

module Focusadmin
  class ArticlesController < ApplicationController
    include CloudinaryHelper
    before_action :set_article, only: [:edit, :update]

    def index
      @q = Article.all.includes(:user).ransack(params[:q])
      @articles = @q.result(distinct: true).order(id: "DESC").page(params[:page]).per(100)

      articles_published = Article.where(status: "published")
      @articles_published_count = articles_published.count
    end

    def edit
    end

    def update
      if params[:article].present? and params[:article][:title].present?
        @article.update(article_params)
        respond_to do |format|
          format.html { redirect_to articles_url, notice: 'article was successfully updated.' }
        end
      else

      	if params[:status_change_button] == "下書きに戻す" || params[:status_change_button] == "Unpublish"
  		    respond_to do |format|
  		      @article.status = "draft"
  		      @article.save
  		      @article_id = @article.id
  		      @action = "change_to_draft"
  		      format.js
  		    end
  		  elsif params[:status_change_button] == "差し戻す" || params[:status_change_button] == "Reject"
  		    respond_to do |format|
  		      @article.status = "draft"
  		      @article.rejected_at = Time.zone.now
  		      @article.reject_reason = params[:reject_reason]
  		      @article.reject_message = params[:reject_message]
  		      @article.save
  		      @action = "reject"
  		      ArticleMailer.review_result_notification_email(@article.user, @article, @action).deliver_later
	      	  format.html { redirect_to review_url, notice: t('.article_has_been_rejected') }
  		    end
        elsif params[:status_change_button] == "公開を予約する" || params[:status_change_button] == "Publish on Schedule"
          respond_to do |format|
            @article.status = "scheduled"

            if params[:facebook].present?
              @article.facebook_post = params[:facebook_post_message] if params[:facebook][:post] == "true" #params come in as strings
            end

            if params[:twitter].present?
              @article.twitter_post = params[:twitter_post_message] if params[:twitter][:post] == "true" #params come in as strings
            end

            article = params[:article]
            @article.publish_on_schedule_at = Time.new(article["publish_on_schedule_at(1i)"].to_i, article["publish_on_schedule_at(2i)"].to_i, article["publish_on_schedule_at(3i)"].to_i, article["publish_on_schedule_at(4i)"].to_i, article["publish_on_schedule_at(5i)"].to_i)
            @article.save
            @action = "scheduled"
            format.html { redirect_to review_url, notice: t('.article_has_been_scheduled') }
          end
        elsif params[:cancel_schedule_button] == "キャンセル" || params[:cancel_schedule_button] == "Cancel"
          respond_to do |format|
            @article.status = "reviewing"
            @article.publish_on_schedule_at = ""
            @article.save
            @article_id = @article.id
            @action = "cancelled_schedule"
            format.js
          end
        else
          respond_to do |format|
            @article.status = "published"
            @article.published_at = Time.zone.now
            @article.save
            @article_id = @article.id
            @action = "publish"
            ArticleMailer.review_result_notification_email(@article.user, @article, @action).deliver_later

            if params[:facebook].present?
              post_to_facebook(params[:facebook_post_message]) if params[:facebook][:post] == "true" #params come in as strings
            end

            if params[:twitter].present?
              tweet(params[:twitter_post_message]) if params[:twitter][:post] == "true" #params come in as strings
            end

            format.html { redirect_to review_url, notice: t('.article_has_been_published') }
          end
        end

      end
    end

    def review
      @q = Article.reviewing.includes(:user).ransack(params[:q])
      @articles = @q.result(distinct: true).order(id: "DESC")
      @articles_waiting_review = Article.reviewing.includes(:user).includes(:category).order(updated_at: :desc)
      @articles_waiting_review_count = @articles_waiting_review.count
    end

    def scheduled
      @q = Article.scheduled.includes(:user).ransack(params[:q])
      @articles = @q.result(distinct: true).order(id: "DESC")
      @scheduled_articles = Article.scheduled.includes(:user).order(publish_on_schedule_at: :asc)
      @scheduled_articles_count = @scheduled_articles.count
    end

	  private
	    def set_article
	      @article = Article.find(params[:id])
	    end

	    def article_params
	      params.require(:article).permit(:title, :excerpt, :body, :slug, :thumbnail, :category_id, :status, :tag_list, :published_at, :rejected_at, :reject_reason, :reject_message, :publish_on_schedule_at, :initially_submitted_at,
          :facebook, :facebook_post_message, :twitter, :twitter_post_message,
          :pr, :sponsor, :pr_start, :pr_end, :pr_pickup)
	    end

      def tweet(twitter_post_message)

        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
          config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
          config.access_token        = ENV['TWITTER_ACCESS_TOKEN']
          config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
        end

        client.update(twitter_post_message + "\nhttps://#{ENV['CANONICAL_HOST']}/#{@article.id}")
      end

      def post_to_facebook(facebook_post_message)

        image_url = cl_image_path(@article.thumbnail, :width => 1200)
        @api = Koala::Facebook::API.new(ENV['FACEBOOK_PAGE_ACCESS_TOKEN'])
        @api.put_wall_post(facebook_post_message, {
          "name" => @article.title,
          "link" => "https://#{ENV['CANONICAL_HOST']}/#{@article.id}", # must be absolute path
          "description" => @article.excerpt,
          "picture" => image_url
        })

      end

  end
end

app/controllers/focusadmin/banners_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class BannersController < ApplicationController
    before_action :set_banner, only: [:show, :edit, :update, :destroy]

    def update_row_order
      @banner = Banner.find(banner_params[:banner_id])
      @banner.row_order_position = banner_params[:row_order_position]
      @banner.save

      render nothing: true
    end

    def index
      @banners = Banner.rank(:row_order)
    end

    def new
      @banner = Banner.new
    end

    def create
      @banner = Banner.new(banner_params)

      respond_to do |format|
        if @banner.save
          format.html { redirect_to banners_url, notice: 'Banner was successfully created.' }
          format.json { render :show, status: :created, location: @banner }
        else
          format.html { render :new }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @banner.update(banner_params)
          format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
          format.json { render :show, status: :ok, location: @banner }
        else
          format.html { render :edit }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @banner.destroy
      respond_to do |format|
        format.html { redirect_to banners_url, notice: 'Banner was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_banner
        @banner = Banner.find(params[:id])
      end

      def banner_params
        params.require(:banner).permit(:banner, :link, :target, :memo, :row_order, :row_order_position, :banner_id)
      end

  end

end

app/controllers/focusadmin/categories_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class CategoriesController < ApplicationController
	  before_action :set_category, only: [:edit, :update, :destroy]

  	def update_row_order
  	  @category = Category.find(category_params[:category_id])
  	  @category.row_order_position = category_params[:row_order_position]
  	  @category.save

  	  render nothing: true
  	end

    def index
    	@categories = Category.rank(:row_order)
    end

	  def new
	    @category = Category.new
	  end

	  def edit
	  end

	  def create
	    @category = Category.new(category_params)

	    respond_to do |format|
	      if @category.save
	        format.html { redirect_to categories_url, notice: 'category was successfully created.' }
	        format.json { render :index, status: :created, location: @category }
	      else
	        format.html { render :new }
	        format.json { render json: @category.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def update
	    respond_to do |format|
	      if @category.update(category_params)
	        format.html { redirect_to categories_url, notice: 'category was successfully updated.' }
	        format.json { render :index, status: :ok, location: @category }
	      else
	        format.html { render :edit }
	        format.json { render json: @category.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  def destroy
	    @category.destroy
	    respond_to do |format|
	      format.html { redirect_to categories_url, notice: 'category was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

	  private
	    def set_category
	      @category = Category.find(params[:id])
	    end

	    def category_params
	      params.require(:category).permit(:name, :description, :slug, :thumbnail, :icon, :row_order, :row_order_position, :category_id)
	    end
  end
end

app/controllers/focusadmin/comments_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class CommentsController < ApplicationController

    def index
      @comments_count = Comment.all.count
    	@comments = Comment.all.includes(:user).order(id: "DESC")
    end

  end
end

app/controllers/focusadmin/contents_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_url, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_url, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :body, :slug, :status)
    end

	end
end

app/controllers/focusadmin/items_controller.rb
require_dependency "focusadmin/application_controller"

module Focusadmin
  class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    def products
      @q = Item.where(item_type: "product").includes(:article).ransack(params[:q])
      @items = @q.result(distinct: true).order(created_at: "DESC").page params[:page]
    end

    def events
      @events = Item.where(item_type: "event").includes(:article).order(event_start_date: :desc)
    end

    private
      def set_item
        @item = Item.find(params[:id])
      end

  end
end

app/helpers/focusadmin/application_helper.rb
module Focusadmin
  module ApplicationHelper

    def curator_page_path(username)
      if username.present?
      escaped_username = URI.escape(username)
      return main_app.root_path + "c/" + escaped_username
      else
        return main_app.root_path
      end
    end

  end
end

app/helpers/focusadmin/articles_helper.rb
module Focusadmin
  module ArticlesHelper

  	def status_view(article)
  		case  article.status
  		when "published" then
  			return t('.published')
      when "reviewing" then
        return t('.reviewing')
  		when "draft" then
        if article.rejected_at.present?
          return t('.rejected')
        else
    			return t('.draft')
        end
  		end
  	end

  end
end

app/helpers/focusadmin/comments_helper.rb
module Focusadmin
  module CommentsHelper

  	def commented_article(comment)
      @article = Article.find(comment.commentable_id)
  	end

  end
end

app/views/layouts/focusadmin/application.html.erb
<!DOCTYPE html>
<html lang="<%= ENV['DEFAULT_LOCALE'] %>">
<head>
  <meta name=”robots” content=”noindex,nofollow” />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag cloudinary_url(@setting.favicon) if @setting.favicon.present? %>
  <%= favicon_link_tag cloudinary_url(@setting.apple_touch_icon), :rel => 'apple-touch-icon', :type => 'image/png' if @setting.apple_touch_icon.present? %>
  <title><%= ENV['SITE_NAME'] + " " + t('.admin') %></title>
  <%= stylesheet_link_tag    "focusadmin/application", media: "all" %>
  <%= javascript_include_tag "focusadmin/application" %>
  <%= cloudinary_js_config %>
    <script>
      $(function() {
          if($.fn.cloudinary_fileupload !== undefined) {
            $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
          }
        });
      $.cloudinary.responsive()
    </script>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
  <style type="text/css">
    .theme_color { color: <%= ENV['COLOR'] %>; }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top theme_color">
	<div class="container-fluid">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <%= link_to (ENV['SITE_NAME'] + " " + t('.admin')), root_path, class: "navbar-brand" %>
	  </div>
	  <div id="navbar" class="navbar-collapse collapse">
	    <ul class="nav navbar-nav navbar-right">
	      <li><%= link_to raw(t('.contents') + " " +fa_icon("sort-down")), "#", class: "dropdown-toggle", data: { toggle: "dropdown" }, role: "button", aria: {haspopup: "true", expanded:"false" } %>
          <ul class="dropdown-menu">
            <li><%= link_to t('.review'), review_path %></li>
            <li><%= link_to t('.scheduled'), scheduled_path %></li>
            <li><%= link_to t('.articles'), articles_path %></li>
            <li><%= link_to t('.pickups'), pickups_path %></li>
            <li><%= link_to t('.features'), features_path %></li>
            <li><%= link_to t('.tags'), tags_path %></li>
            <li><%= link_to t('.banners'), banners_path %></li>
          </ul></li>
        <li class="dropdown"><%= link_to raw(t('.items') + " " +fa_icon("sort-down")), "#", class: "dropdown-toggle", data: { toggle: "dropdown" }, role: "button", aria: {haspopup: "true", expanded:"false" } %>
          <ul class="dropdown-menu">
            <li><%= link_to t('.products'), items_products_path %></li>
            <li><%= link_to t('.events'), items_events_path %></li>
          </ul>
        </li>
        <li class="dropdown"><%= link_to raw(t('.users') + " " +fa_icon("sort-down")), "#", class: "dropdown-toggle", data: { toggle: "dropdown" }, role: "button", aria: {haspopup: "true", expanded:"false" } %>
          <ul class="dropdown-menu">
            <li><%= link_to t('.users_list'), users_path %></li>
            <% if ENV['DEFAULT_ROLE'] == "user" %><li><%= link_to t('.curator_application_list'), curator_applicants_path %></li><% end %>
          </ul>
        </li>
        <!-- <li><%= link_to t('.ads'), '#' %></li> -->
	      <li><%= link_to t('.information'), information_index_path %></li>
        <li><%= link_to t('.comments'), comments_path %></li>
	      <li><%= link_to t('.settings'), settings_path %></li>
	      <li><%= link_to t('.view_site'), main_app.root_path %></li>
	    </ul>
	  </div>
</div>
</nav>

<div class="container-fluid">
    <% if flash %>
      <% flash.each do |type, msg| %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= msg %>
        </div>
      <% end %>
    <% end %>
	<%= yield %>
</div>

<footer>
  <div class="page_top">
    <a class="page-top" href="#">PAGE TOP</a>
  </div>
</footer>

</body>
</html>